package finalproject;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Giri Kusuma
 */
public class crudFrame extends javax.swing.JFrame {
    
    private DefaultTableModel model;
    /**
     * Creates new form crudForm
     */
    public crudFrame() throws SQLException {
        initComponents();
        kodebarang();
        model = new DefaultTableModel();
        
        Tabel_Buku.setModel(model);
        
        model.addColumn("Kode Produk");
        model.addColumn("Nama Produk");
        model.addColumn("Harga");
        model.addColumn("Jenis");
        model.addColumn("Stock");
        
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kode_label = new javax.swing.JLabel();
        judul_label = new javax.swing.JLabel();
        pengarang_label = new javax.swing.JLabel();
        penerbit_label = new javax.swing.JLabel();
        kode_produk = new javax.swing.JTextField();
        nama_produk = new javax.swing.JTextField();
        harga_produk = new javax.swing.JTextField();
        stock_produk = new javax.swing.JTextField();
        tambah = new javax.swing.JButton();
        ubah = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        TabelBuku = new javax.swing.JScrollPane();
        Tabel_Buku = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        pilihan = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kode_label.setText("Kode Produk");

        judul_label.setText("Nama Produk");

        pengarang_label.setText("Harga");

        penerbit_label.setText("Stock");

        kode_produk.setEnabled(false);
        kode_produk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kode_produkActionPerformed(evt);
            }
        });

        tambah.setText("Tambah");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });

        ubah.setText("Ubah");
        ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahActionPerformed(evt);
            }
        });

        hapus.setText("Hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        Tabel_Buku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tabel_Buku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabel_BukuMouseClicked(evt);
            }
        });
        TabelBuku.setViewportView(Tabel_Buku);

        jLabel1.setText("Jenis");

        pilihan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Makanan", "Minuman" }));
        pilihan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tambah)
                                .addGap(37, 37, 37)
                                .addComponent(ubah)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(hapus))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(judul_label)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(kode_label)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(kode_produk, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nama_produk, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(penerbit_label)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pengarang_label)
                                    .addComponent(jLabel1))
                                .addGap(60, 60, 60)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(stock_produk, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                                    .addComponent(harga_produk, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                                    .addComponent(pilihan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(TabelBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TabelBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kode_label)
                            .addComponent(kode_produk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(judul_label)
                            .addComponent(nama_produk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pengarang_label)
                            .addComponent(harga_produk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(pilihan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(penerbit_label)
                            .addComponent(stock_produk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tambah)
                            .addComponent(ubah)
                            .addComponent(hapus))))
                .addContainerGap(106, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kode_produkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kode_produkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kode_produkActionPerformed

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        try {
            // TODO add your handling code here:
            Connection c = Koneksi.getKoneksi(); 
            c.createStatement().executeUpdate("insert into produk values"+"('"+kode_produk.getText()+"','"+nama_produk.getText()+"','"+harga_produk.getText()+"','"+pilihan.getSelectedItem()+"','"+stock_produk.getText()+"')");
            loadData();
            reset();
            Monitor ad = new Monitor();
            ad.setVisible(true);
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(crudFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tambahActionPerformed

    private void ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahActionPerformed
        try {
            Connection c = Koneksi.getKoneksi();
            c.createStatement().executeUpdate("update produk set nama_produk='"+nama_produk.getText()+"',harga_produk='"+harga_produk.getText()+"',jenis='"+pilihan.getSelectedItem()+"',stock='"+stock_produk.getText()+"' where kode_produk='"+kode_produk.getText()+"'");
            loadData();
            reset();
            Monitor ad = new Monitor();
            ad.setVisible(true);
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(crudFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ubahActionPerformed

    private void Tabel_BukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabel_BukuMouseClicked
        // TODO add your handling code here:
        int i = Tabel_Buku.getSelectedRow();
        if(i>-1){
            kode_produk.setText(model.getValueAt(i, 0).toString());
            nama_produk.setText(model.getValueAt(i, 1).toString());
            harga_produk.setText(model.getValueAt(i, 2).toString());
            pilihan.setSelectedItem(model.getValueAt(i, 3).toString());
            stock_produk.setText(model.getValueAt(i, 4).toString());
        }
    }//GEN-LAST:event_Tabel_BukuMouseClicked

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        try {
            Connection c = Koneksi.getKoneksi();
            c.createStatement().executeUpdate("delete from produk where kode_produk='"+kode_produk.getText()+"'");
            loadData();
            reset();
            Monitor ad = new Monitor();
            ad.setVisible(true);
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(crudFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_hapusActionPerformed

    private void pilihanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pilihanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(crudFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(crudFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(crudFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(crudFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new crudFrame().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(crudFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane TabelBuku;
    private javax.swing.JTable Tabel_Buku;
    private javax.swing.JButton hapus;
    private javax.swing.JTextField harga_produk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel judul_label;
    private javax.swing.JLabel kode_label;
    private javax.swing.JTextField kode_produk;
    private javax.swing.JTextField nama_produk;
    private javax.swing.JLabel penerbit_label;
    private javax.swing.JLabel pengarang_label;
    private javax.swing.JComboBox<String> pilihan;
    private javax.swing.JTextField stock_produk;
    private javax.swing.JButton tambah;
    private javax.swing.JButton ubah;
    // End of variables declaration//GEN-END:variables

    private void loadData() throws SQLException {
        //menghapus seluruh data
        model.getDataVector().removeAllElements();
        //memberi tahu bahwa data telah kosong
        model.fireTableDataChanged();
        
        try{
            Connection c = Koneksi.getKoneksi();
            Statement s = c.createStatement();
            String sql = "SELECT * FROM produk";
            ResultSet r = s.executeQuery(sql);
            while(r.next()){
                //lakukan penelusuran baris
                Object[] o = new Object [5];
                o[0] = r.getString("kode_produk");
                o[1] = r.getString("nama_produk");
                o[2] = r.getString("harga_produk");
                o[3] = r.getString("jenis");
                o[4] = r.getString("stock");
            }
            r.close();
            s.close();
            tampilkan();
        } catch (SQLException e){
            System.out.println("Terjadi Error");
        }
    }

    private void tampilkan() {
        int row = Tabel_Buku.getRowCount();
        for(int a=0;a<row;a++){
            model.removeRow(0);
        }
        try{
            Connection c = Koneksi.getKoneksi();
            ResultSet r = c.createStatement().executeQuery("select * from produk");
            while(r.next()){
                String data[] = {r.getString(1),r.getString(2),r.getString(3),r.getString(4),r.getString(5)};
                model.addRow(data);
            }
        } catch (SQLException ex){
            Logger.getLogger(crudFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void reset() {
        kode_produk.setText("");
        nama_produk.setText("");
        harga_produk.setText("");
        stock_produk.setText("");
    }

    private void kodebarang() {
        try {
            Connection c = Koneksi.getKoneksi();
            String sql = "select * from produk order by kode_produk desc";
            Statement s = c.createStatement();
            ResultSet r = s.executeQuery(sql);
            if(r.next()){
                String id = r.getString("kode_produk").substring(1);
                String i = "" + (Integer.parseInt(id)+1);
                String nol = "";
                if(i.length()==1){
                    nol = "000";
                } else if (i.length()==2){
                    nol = "00";
                } else if (i.length()==3){
                    nol = "0";
                } else {
                    nol = "";
                }
                kode_produk.setText("P"+nol+i);
            } else {
                kode_produk.setText("P0001");
            }
        } catch (Exception e){
            System.out.println("");
        }
    }
}
    
