/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalproject;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Giri Kusuma
 */
public class Monitor extends javax.swing.JFrame {

    /**
     * Creates new form Monitor
     */
    DefaultTableModel model;
    int jumlah = 0;
    public Monitor() {
        initComponents();
        kode();
        model = new DefaultTableModel();
        
        TabelPembelian.setModel(model);
        
        model.addColumn("Kode");
        model.addColumn("Nama");
        model.addColumn("Harga");
        model.addColumn("Jenis");
        model.addColumn("Stock");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tulisankasir = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelPembelian = new javax.swing.JTable();
        cari = new javax.swing.JTextField();
        cariButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        kodebeli = new javax.swing.JTextField();
        namabeli = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        hargabeli = new javax.swing.JTextField();
        jumlahbeli = new javax.swing.JTextField();
        masukanButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        idpembeli = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        gudangButton = new javax.swing.JButton();
        dataP = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tulisankasir.setFont(new java.awt.Font("Montserrat Alternates Light", 0, 24)); // NOI18N
        tulisankasir.setText("Selamat berbelanja...");

        TabelPembelian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TabelPembelian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelPembelianMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelPembelian);

        cariButton.setText("Cari");
        cariButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Kode Produk");

        jLabel2.setText("Nama Produk");

        jLabel3.setText("Harga Produk");

        kodebeli.setEnabled(false);

        namabeli.setEnabled(false);

        jLabel4.setText("Jumlah");

        hargabeli.setEnabled(false);

        masukanButton.setText("Masukan");
        masukanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masukanButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("ID");

        idpembeli.setEnabled(false);
        idpembeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idpembeliActionPerformed(evt);
            }
        });

        jButton1.setText("Bayar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        gudangButton.setText("Gudang");
        gudangButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gudangButtonActionPerformed(evt);
            }
        });

        dataP.setText("Data Penjualan");
        dataP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cari)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cariButton))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(gudangButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dataP)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jumlahbeli)
                                    .addComponent(hargabeli)
                                    .addComponent(kodebeli)
                                    .addComponent(namabeli)
                                    .addComponent(idpembeli, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(masukanButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(21, 21, 21))))
                    .addComponent(tulisankasir))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(tulisankasir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cariButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gudangButton)
                    .addComponent(dataP))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(idpembeli, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(kodebeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(namabeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(hargabeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jumlahbeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(masukanButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cariButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariButtonActionPerformed
        int row = TabelPembelian.getRowCount();
        for(int a=0;a<row;a++){
            model.removeRow(0);
        }
        try{
            Connection c = Koneksi.getKoneksi();
            ResultSet r = c.createStatement().executeQuery("select * from produk where kode_produk like '%"+cari.getText()+"%' or nama_produk like '%"+cari.getText()+"%' and stock > 0");
            while(r.next()){
                String data[] = {r.getString(1),r.getString(2),r.getString(3),r.getString(4), r.getString(5)};
                model.addRow(data);
            }
        } catch (SQLException ex){
            Logger.getLogger(Monitor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cariButtonActionPerformed

    private void TabelPembelianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelPembelianMouseClicked
        int baris = TabelPembelian.getSelectedRow();
        kodebeli.setText(TabelPembelian.getModel().getValueAt(baris, 0).toString());
        namabeli.setText(TabelPembelian.getModel().getValueAt(baris, 1).toString());
        hargabeli.setText(TabelPembelian.getModel().getValueAt(baris, 2).toString());
    }//GEN-LAST:event_TabelPembelianMouseClicked

    private void masukanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masukanButtonActionPerformed
       String id = idpembeli.getText();
       String kode = kodebeli.getText();
       String br = namabeli.getText();
       String harga = hargabeli.getText();
       int total =Integer.parseInt(harga);
       int jumlah = Integer.parseInt(jumlahbeli.getText());
       int ttl = total*jumlah;
       try {
            Connection c = Koneksi.getKoneksi();
            c.createStatement().executeUpdate("insert into pembeli values"+"('"+id+"','"+kode+"','"+br+"','"+harga+"','"+jumlah+"','"+total+"','Belum Lunas')");
            resetbeli();
       } catch (SQLException e) {
           Logger.getLogger(Monitor.class.getName()).log(Level.SEVERE, null, e);
       }
    }//GEN-LAST:event_masukanButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String id = idpembeli.getText();
        String kode = kodebeli.getText();
        String br = namabeli.getText();
        String harga = hargabeli.getText();
        int total =Integer.parseInt(harga);
        int jumlah = Integer.parseInt(jumlahbeli.getText());
        if(kode!=""){
            try {
                Connection c = Koneksi.getKoneksi();
                c.createStatement().executeUpdate("insert into pembeli values"+"('"+id+"','"+kode+"','"+br+"','"+harga+"','"+jumlah+"','"+total+"','Belum Lunas')");
                ResultSet r = c.createStatement().executeQuery("select * from pembeli where ID='"+id+"' and keterangan ='Belum Lunas'");
                while(r.next()){
                    int je = Integer.parseInt(r.getString(5));
                    String cd = r.getString(2);
                    System.out.println(cd);
                    System.out.println(je);
                    c.createStatement().executeUpdate("update produk as p inner join pembeli as pe on p.kode_produk = pe.kode set p.stock = p.stock - "+je+" where pe.keterangan = 'Belum Lunas' and p.kode_produk='"+cd+"'");
                }
                reset();
                Pembayaran pm = new Pembayaran();
                pm.setVisible(true);
                dispose();
            } catch (SQLException e) {
//               JOptionPane.showMessageDialog(rootPane, "");
                Pembayaran pm = new Pembayaran();
                pm.setVisible(true);
                dispose();  
            }
        } else {
            Connection c = Koneksi.getKoneksi();
            try {
                ResultSet r = c.createStatement().executeQuery("select * from pembeli where ID='"+id+"' and keterangan ='Belum Lunas'");
                while(r.next()){
                    int je = Integer.parseInt(r.getString(5));
                    String cd = r.getString(2);
                    System.out.println(cd);
                    System.out.println(je);
                    c.createStatement().executeUpdate("update produk as p inner join pembeli as pe on p.kode_produk = pe.kode set p.stock = p.stock - "+je+" where pe.keterangan = 'Belum Lunas' and p.kode_produk='"+cd+"'");
                }
                reset();
                Pembayaran pm = new Pembayaran();
                pm.setVisible(true);
                dispose();
            } catch (SQLException ex) {
                Logger.getLogger(Monitor.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void gudangButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gudangButtonActionPerformed
        // TODO add your handling code here:
        crudFrame cd;
        try {
            cd = new crudFrame();
            cd.setVisible(true);
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(Monitor.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_gudangButtonActionPerformed

    private void dataPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataPActionPerformed
        // TODO add your handling code here:
        penjualan pj = new penjualan();
        pj.setVisible(true);
        dispose();
    }//GEN-LAST:event_dataPActionPerformed

    private void idpembeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idpembeliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idpembeliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Monitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Monitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Monitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Monitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Monitor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelPembelian;
    private javax.swing.JTextField cari;
    private javax.swing.JButton cariButton;
    private javax.swing.JButton dataP;
    private javax.swing.JButton gudangButton;
    private javax.swing.JTextField hargabeli;
    private javax.swing.JTextField idpembeli;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jumlahbeli;
    private javax.swing.JTextField kodebeli;
    private javax.swing.JButton masukanButton;
    private javax.swing.JTextField namabeli;
    private javax.swing.JLabel tulisankasir;
    // End of variables declaration//GEN-END:variables

    private void resetbeli() {
        kodebeli.setText("");
        namabeli.setText("");
        hargabeli.setText("");
        jumlahbeli.setText("");
    }

    private void reset() {
        kodebeli.setText("");
        namabeli.setText("");
        hargabeli.setText("");
        jumlahbeli.setText("");
        idpembeli.setText("");
    }
    
    private void kode() {
        try {
            Connection c = Koneksi.getKoneksi();
            String sql = "select * from pembeli order by ID desc";
            Statement s = c.createStatement();
            ResultSet r = s.executeQuery(sql);
            if(r.next()){
                String id = r.getString("ID").substring(1);
                String i = "" + (Integer.parseInt(id)+1);
                String nol = "";
                if(i.length()==1){
                    nol = "000";
                } else if (i.length()==2){
                    nol = "00";
                } else if (i.length()==3){
                    nol = "0";
                } else {
                    nol = "";
                }
                idpembeli.setText("B"+nol+i);
            } else {
                idpembeli.setText("B0001");
            }
        } catch (Exception e){
            System.out.println("");
        }
    }
}
