/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalproject;

import java.io.File;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Giri Kusuma
 */
public class Pembayaran extends javax.swing.JFrame {
    JasperReport jasperReport;
    JasperDesign jasperDesign;
    JasperPrint jasperPrint;
    Map<String, Object> param = new HashMap<String, Object>();
    DefaultTableModel model1;
    int jumlah = 0;
    int sisa = 0;
    /**
     * Creates new form Pembayaran
     */
    public Pembayaran() {
        initComponents();
        
        model1 = new DefaultTableModel();
        
        TabelPembeli.setModel(model1);
        
        model1.addColumn("ID");
        model1.addColumn("Kode");
        model1.addColumn("Produk");
        model1.addColumn("Harga");
        model1.addColumn("Jumlah");
        model1.addColumn("Total");
        
        tampilkan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelPembeli = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelPembeli = new javax.swing.JTable();
        labelTotal = new javax.swing.JLabel();
        kembalian = new javax.swing.JLabel();
        cashPembeli = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        hapusID = new javax.swing.JTextField();
        hapuskode = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelPembeli.setFont(new java.awt.Font("Montserrat Alternates Light", 0, 24)); // NOI18N
        labelPembeli.setText("Customer : ");

        TabelPembeli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TabelPembeli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelPembeliMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelPembeli);

        labelTotal.setFont(new java.awt.Font("Montserrat Alternates Light", 0, 24)); // NOI18N
        labelTotal.setText("Total : Rp. ");

        kembalian.setFont(new java.awt.Font("Montserrat Alternates Light", 0, 24)); // NOI18N
        kembalian.setText("Kembalian : Rp.");

        cashPembeli.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Montserrat Alternates Light", 0, 24)); // NOI18N
        jLabel2.setText("Cash : Rp.");

        jButton1.setText("Cetak");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("hapus");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        hapusID.setEnabled(false);

        hapuskode.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(cashPembeli, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(kembalian)
                                    .addComponent(labelTotal)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)))
                        .addComponent(jButton2))
                    .addComponent(labelPembeli)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(hapusID, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hapuskode, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelPembeli)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelTotal)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cashPembeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2))
                        .addGap(32, 32, 32)
                        .addComponent(kembalian)
                        .addGap(31, 31, 31)
                        .addComponent(jButton1)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hapusID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hapuskode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int bayar ;
        String id = "";
        bayar= Integer.parseInt(cashPembeli.getText());
        sisa = bayar - jumlah;
        if(sisa>=0){
            this.kembalian.setText("Kembalian : Rp."+sisa);
            try{
                Connection c = Koneksi.getKoneksi();
                ResultSet r = c.createStatement().executeQuery("select * from pembeli where keterangan = 'Belum Lunas'");
                while(r.next()){
                    if(id==""){
                        id = r.getString(1);
                    }
                }
                File file = new File("src/finalproject/cetak.jrxml");
                jasperDesign = JRXmlLoader.load(file);
                param.put("id", id);
                jasperReport = JasperCompileManager.compileReport(jasperDesign);
                jasperPrint = JasperFillManager.fillReport(jasperReport, param, c);
                JasperViewer.viewReport(jasperPrint, false);
                c.createStatement().executeUpdate("update pembeli set keterangan='Lunas' where  ID='"+id+"'");
                Monitor m = new Monitor();
                m.setVisible(true);
                dispose();
            } catch (SQLException ex){
                Logger.getLogger(Pembayaran.class.getName()).log(Level.SEVERE, null, ex);
            } catch (JRException ex) {
                Logger.getLogger(Pembayaran.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Uang tidak cukup");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int bayar ;
        String id = "";
        bayar= Integer.parseInt(cashPembeli.getText());
        sisa = bayar - jumlah;
         if(sisa>=0){
            this.kembalian.setText("Kembalian : Rp."+sisa);
         } else {
            JOptionPane.showMessageDialog(rootPane, "Uang tidak cukup");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void TabelPembeliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelPembeliMouseClicked
        // TODO add your handling code here:
        int i = TabelPembeli.getSelectedRow();
        if(i>-1){
            hapusID.setText(model1.getValueAt(i, 0).toString());
            hapuskode.setText(model1.getValueAt(i, 1).toString());
        }
    }//GEN-LAST:event_TabelPembeliMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String ID = hapusID.getText();
        String kode = hapuskode.getText();
         try {
            Connection c = Koneksi.getKoneksi();
            c.createStatement().executeUpdate("delete from pembeli where ID='"+ID+"' and kode='"+kode+"' and keterangan='Belum Lunas'");
            tampilkan();
            resethapus();
        } catch (SQLException ex) {
            Logger.getLogger(crudFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pembayaran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelPembeli;
    private javax.swing.JTextField cashPembeli;
    private javax.swing.JTextField hapusID;
    private javax.swing.JTextField hapuskode;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel kembalian;
    private javax.swing.JLabel labelPembeli;
    private javax.swing.JLabel labelTotal;
    // End of variables declaration//GEN-END:variables

    private void tampilkan() {
        int row = TabelPembeli.getRowCount();
        String id = "";
        for(int a=0;a<row;a++){
            model1.removeRow(0);
        }
        try{
            Connection c = Koneksi.getKoneksi();
            ResultSet r = c.createStatement().executeQuery("select * from pembeli where keterangan = 'Belum Lunas'");
            while(r.next()){
                if(id==""){
                    id = r.getString(1);
                }
                if(id.equals(r.getString(1))){
                    int j = (Integer.parseInt(r.getString(4)))*(Integer.parseInt(r.getString(5)));
                    String data [] = {r.getString(1),r.getString(2),r.getString(3),r.getString(4),r.getString(5), Integer.toString(j)};
                    model1.addRow(data);
                    jumlah = jumlah + j;
                }
            }
        } catch (SQLException ex){
            Logger.getLogger(Pembayaran.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.labelPembeli.setText("ID Customer : " + id);
        this.labelTotal.setText("Total : Rp. " + jumlah);
    }

    private void resethapus() {
        hapusID.setText("");
        hapuskode.setText("");
    }
}
